version: '3.8'

services:
  xlmr_service:
    build: ./xlmr_service
    ports:
      - "8001:8001"
    environment:
      - MODEL_DIR=/app/model/xlm-r-phishing-final

  gmail_service:
    build: ./gmail_service
    environment:
      - REDIS_URL=redis://redis:6379
      - DETECTOR_URL=http://xlmr_service:8001/predict
    ports:
      - "8002:8002"
    depends_on:
      xlmr_service:
        condition: service_started
      redis:
        condition: service_healthy

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Use command to disable protected mode and enable background saving
    command: ["redis-server", "--protected-mode", "no", "--save", "60", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

volumes:
  redis_data: